package com.glaway.sddq.back.Interface.webservice.mdm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MdmToMroService", targetNamespace = "http://mdm.webservice.Interface.back.sddq.glaway.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MdmToMroService {


    /**
     * 
     * @param mdmXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String toMroMdmPersonData(
        @WebParam(name = "mdmXml", partName = "mdmXml")
        String mdmXml);

    /**
     * 
     * @param mdmXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String toMroMdmDeptData(
        @WebParam(name = "mdmXml", partName = "mdmXml")
        String mdmXml);

    /**
     * 
     * @param mdmXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String toMroMdmPostData(
        @WebParam(name = "mdmXml", partName = "mdmXml")
        String mdmXml);

    /**
     * 
     * @param mdmXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String toMroMdmCustinfoData(
        @WebParam(name = "mdmXml", partName = "mdmXml")
        String mdmXml);

    /**
     * 
     * @param mdmXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String toMroMdmCompanyData(
        @WebParam(name = "mdmXml", partName = "mdmXml")
        String mdmXml);

    /**
     * 
     * @param mdmXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String toMroMdmItemData(
        @WebParam(name = "mdmXml", partName = "mdmXml")
        String mdmXml);

}
