
package com.glaway.sddq.config.sbom.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PlmToMroServiceImpService", targetNamespace = "http://webservice.sbom.config.sddq.glaway.com/", wsdlLocation = "http://192.168.112.41:8080/gwmro/mroservice/plmTomro?wsdl")
public class PlmToMroServiceImpService
    extends Service
{

    private final static URL PLMTOMROSERVICEIMPSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://192.168.112.41:8080/gwmro/mroservice/plmTomro?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PLMTOMROSERVICEIMPSERVICE_WSDL_LOCATION = url;
    }

    public PlmToMroServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlmToMroServiceImpService() {
        super(PLMTOMROSERVICEIMPSERVICE_WSDL_LOCATION, new QName("http://webservice.sbom.config.sddq.glaway.com/", "PlmToMroServiceImpService"));
    }

    /**
     * 
     * @return
     *     returns PlmToMroService
     */
    @WebEndpoint(name = "PlmToMroServiceImpPort")
    public PlmToMroService getPlmToMroServiceImpPort() {
        return (PlmToMroService)super.getPort(new QName("http://webservice.sbom.config.sddq.glaway.com/", "PlmToMroServiceImpPort"), PlmToMroService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PlmToMroService
     */
    @WebEndpoint(name = "PlmToMroServiceImpPort")
    public PlmToMroService getPlmToMroServiceImpPort(WebServiceFeature... features) {
        return (PlmToMroService)super.getPort(new QName("http://webservice.sbom.config.sddq.glaway.com/", "PlmToMroServiceImpPort"), PlmToMroService.class, features);
    }

}
