
package com.glaway.sddq.config.sbom.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PlmToMroService", targetNamespace = "http://webservice.sbom.config.sddq.glaway.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PlmToMroService {


    /**
     * 
     * @param itemnum
     * @param ebomXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String toMroEbomData(
        @WebParam(name = "itemnum", partName = "itemnum")
        String itemnum,
        @WebParam(name = "ebomXml", partName = "ebomXml")
        String ebomXml);

}
